services:
  - type: web
    name: django-web
    env: python
    buildCommand: "./build.sh"
    startCommand: gunicorn myproject.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: myproject.settings
      - key: DATABASE_URL
        fromDatabase:
          name: mydb
          property: connectionString
